### PR TITLE
Unify MACH-Aero documentation

### PR DESCRIPTION
**Pull request by nwu63**
I combined the various MACH-Aero related repos into a single repository. Closes mdolab/docs#38. More specifically:
- removed git submodules present in `MACH-Aero` since I don't think they are useful
- merged `docs` into this repo, I also preserved the git history which is why this PR has so many commits
- merged `MACH-Aero-tutorials` into this repo. I did not preserve the git history for this merge
- updated some descriptions of MACH-Aero and its modules
- updated the repository layout to be consistent
- various formatting changes

After this is merged, the two repos (`docs` and `MACh-Aero-tutorial` will be deprecated and archived on GitHub). There are corresponding changes to be made to the lab website to reflect this change.

Also note that PR build has not been enabled yet (I have contacted support), but in the mean time you can preview the changes on the [branch build here](https://mdolab-mach-aero.readthedocs-hosted.com/en/merge-repos-2/).

The things I wanted someone to review are:
- overall structure/layout of the site
- description of MACH-Aero and its modules

### CODE REVIEW

**Comment by nwu63** [comment]
I think it's fine, because the installation instructions for each repo also talks about installing dependencies such as CGNS/PETSc, and redirect users to this site. So I don't think that's a problem.

**Comment by yqliaohk** [comment]
> I think it's fine, because the installation instructions for each repo also talks about installing dependencies such as CGNS/PETSc, and redirect users to this site. So I don't think that's a problem.

Ok, yeah, that makes sense. Is it normal that the redirect link is broken in the branch build?

**Comment by nwu63** [comment]
> Ok, yeah, that makes sense. Is it normal that the redirect link is broken in the branch build?

Shouldn't be, which links are broken?

**Comment by shamsheersc19** [comment]
Did a quick skim and it looks good. Pushed a couple things:
* Added cgnsUtilities to the optional packages
* Changed some links to GitHub from BitBucket

**Pull request merged**
