### PR TITLE
Link to the Correct Repo for Files

### PR DESCRIPTION
**Pull request by akleb**
## Purpose
We are linking to the old repo for the files for this tutorial. The old files do not follow our currently stricter option requirements. Also the old tutorial is archived, we should really be linking to the current one.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by akleb** [comment]
I did not see any other links to the files, so I think this is it. If anyone knows of other places we might be linking incorrectly, we should check those.

**Review by nwu63 — APPROVED** [review]

**Review by nwu63 — CHANGES_REQUESTED** [review]
Actually line 59 has the wrong link also

**Comment by akleb** [comment]
> Actually line 59 has the wrong link also

Guess I didn't check very closely.

**Review by nwu63 — APPROVED** [review]

**Comment by nwu63** [comment]
`grep` is your friend :)

**Comment by akleb** [comment]
Yeah I grepped before submitting the second commit lol

**Pull request merged**
